### ISSUE TITLE
Glad to See This

### ISSUE THREAD

**Issue by cogdog** [vcualtlab/list-remote-comments#1]
A good idea to append it to posts. The reason I took it off of ds106 was it was used on the main archive pages and the assignments; it bogged down for the time to do multiple remote requests for RSS. I ought to do this via pulls, but some questions:
- I like that there is a cache time for doing the requests, shouldn't post_meta `rc_comment_count_stamp` be updated after checking (or is that done somewhere else).
- Likewise I am not seeing where the post_meta for `rc_comment_count` is updated either.
- It might be worth adding some CSS id/class to the output so it can be styled

Glad to see this, am hoping to work on a package of other FWP themes for stuff I have been doing manually, let's team up.

**Comment by luetkemj** [comment]
- yep
- yep
- and yep

I started with the remote comments plugin and mushed some of my own stuff after getting access to what I needed. Will clean this up soon and look closer at caching and some of the other bits.

This is a pretty dirty implementation at the moment. Gets the job done. But could do it better.

Thanks for the input :+1:

**Comment by luetkemj** [comment]
> It might be worth adding some CSS id/class to the output so it can be styled

good call - added at 7ebf48186c864e0d8964c9ce7134c8c469971a83

> shouldn't post_meta rc_comment_count_stamp be updated after checking

fixed at 2afc609f001de5b955ba1bb895fa28753cbe0b58

> Likewise I am not seeing where the post_meta for rc_comment_count is updated either.

updated at 2afc609f001de5b955ba1bb895fa28753cbe0b58

Although I'm trying to figure out why that's in there at all...  I'm not after the comments count anymore. So I guess I should be saving the $output to post_meta. I could then get rid of 'lrc_comment_count' and add something like 'lrc_comment_list'

**Comment by luetkemj** [comment]
Now we're caching with :fire: 

e15d6c529c7c0a5ab0222438628ce93735d7a4df
